spring.application.name=MS_reservas
server.port=8090

spring.datasource.url=jdbc:mysql://localhost:3306/sistema_reservas?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.clients.vuelos-url=http://localhost:8081
app.clients.clientes-url=http://localhost:9090
app.clients.flota-url=http://localhost:8082
app.clients.pagos-url=http://localhost:9091
